### ISSUE TITLE
The Punch Script

### ISSUE THREAD

**Issue by petarov** [petarov/game-off-2017#3]
Last edit: `10-Nov-2017 23:30 UTC+0`
Last edited by: @petarov

The Kickpunch Script
================

(_Warning! Cheezy content detected._ 🧀 )

# Characters

Name | Role
-- | --
Brian Freezby 🏃  | Main protagnoist
Gloria Freezby 👧  | Brian’s wife
Dido 🐕  | Brian and Gloria’s dog
Arkian Joel | Brian’s arch enemy (Game boss)
Bo | A mid-level boss

# Foes

Name | Image | Description
-- | -- | --
P1 | ![story_foe_1](https://user-images.githubusercontent.com/547597/32537909-8078bd50-c464-11e7-93b4-68fce4a3f07a.png) | Level 1 NPC minion. Fists attack.
P2 (Big Joe) | ![story_foe_bigjoe](https://user-images.githubusercontent.com/547597/32538137-5209109a-c465-11e7-887e-d934ce4a59cc.png) | Level 2 NPC minion. Has more health, does more damage.
K1 | ![story_foe_2](https://user-images.githubusercontent.com/547597/32537929-901b95c0-c464-11e7-9d0a-a20fb2c06be3.png) | Level 1 NPC minion. Kicks attack.
K2 (Mino) | ![story_foe_bigjoe](https://user-images.githubusercontent.com/547597/32537950-9c90a714-c464-11e7-972e-ca4ec4d3d83a.png) | Level 2 NPC minion. Has more health, does more damage.
Bo | ![story_foe_bo](https://user-images.githubusercontent.com/547597/32537941-96673254-c464-11e7-96c8-d717d3db0e62.png) | Boss Level. Fists attack.
Arkian Joel  | n/a | Boss level. _TODO_

# Setting

Brian and Gloria are back in their home town for the weekend and are taking a stroll on Shaker St. Suddenly, they are approached by a group of hooligans who block their way forwards. One of them, visibly bigger than the others, steps out of the group. It is Brian’s old school rival - **Arkian Joel**. Arkian does some smack talk and orders a bunch of hooligans to grab Gloria and Dido. He then orders **Bo**, a gang member, to take care of the *"Brian problem"* and the group leaves. 

Bo leaves few thugs to *finish* Brian off. Brian faces the bad guys in fight and after defeating them continues down on Shaker St. determined to find Arkian and save his wife and dog.

# Chapters

## Opening Scene (Intro)

Gloria, Brian and Dido are positioned on the left side of the screen. A short dialog follows between Gloria and Brian. 

Suddenly Arkian, Bo and a few thugs appear walking towards Brian's from the right side of the screen. The music changes and dialogs are exchanged.

The thugs (or Bo and some P1) pick up Gloria and Dido (their sprites hovering above the thugs' sprites) and move away from Brian (they move to the right pass the screen edge). Dialogs are exchanged between Brian and Arkian and the scene ends.

### Dialog
_TODO_

## Act 1 - Defeating Bo's Thugs

Brian needs to defeat Bo's thugs and continue his search on Shaker St. The act finishes with Brian defeating the thugs.

This act also serves as a tutorial. The player will be shown the controls to play with, the moves and so on.

### Attack Waves
* Wave 1 - 2x P1 foes.
* Wave 2 - 3x P1 foes.

## Act 2 - Local Drunks
While walking ahead, a door on the street opens. Brian faces a group of drunks from the local bar. He needs to defeat them before continuing to the next act.
The group consists of 3 waves.

### Attack Waves
* Wave 1 - 3x P1 foes.
* Wave 2 - 5x P1 foes.
* Wave 3 - 3x P1 foes + 1x P2 foe.

## Act 3 - Fighting Bo's Gang
Bo, a member of Arkian’s gang is left to deal with Brian. Brian needs to defat Bo and continue his search down on Shaker St. The act finishes with Brian defeating the boss level - Bo.

### Attack Waves
* Wave 1 - 3x K1 foes.
* Wave 2 - 2x K1 + 3x P1 foes.
* Wave 3 - 3x K1 foes + 1x Bo. 
  - Every time Bo's health diminishes by `25%` we will spawn 1x P1 and 1x K1 foes.

## Act 4 - Arkian's Gang. An Elevator Action.
Brian needs to get to the very top of a city building in order to locate Arkian Joel. He hopes to also find there Gloria and Dido. While taking the elevator he is suddenly attacked by Arkian's gang.

**Note**. In this level, because the elevator will be moving up, enemies will have to drop from above or something. We can't have them simply walking in from the left or right edge of the screen. Also, we could include the ability to throw enemies off the elevator. This has to be addressed in the game mechanics!

### Attack Waves
_TODO_

## Act 5 - The Roof Fight
Brian is on the top of a city building (on the roof). He has to combat a bunch of enemies before facing Arkian. The final fight is between Arkian and him, as well as some level 1 foes.

### Dialog
_TODO_

Defeating Arkian ends the game and Brian wins.

### Attack Waves

* Wave 1 - 2x P1 + 2x K1 foes.
* Wave 2 - 1x P2 + 1x K2 foes.
* Wave 3 - 1x Arkian + 2x K1 foes + 2x P1 foes. 
  - Every time Arkian's health diminishes by `25%` we will spawn 1x P2 / K2 foe.

## Finale
Brian, Gloria and Dido are reunited and continue their weekend walk on Shaker St.

### Dialog
_TODO_

Roll credits.

**Comment by petarov** [comment]
I just realized what a poor choice of clothing Brian's got for a weekend walk. 😆 
 
![brian](https://user-images.githubusercontent.com/547597/32516568-0a5648f0-c404-11e7-9f25-5a01c80cad85.gif)

**Comment by n3tn0de** [comment]
Story's basically a mix of Double Dragon (get your woman back) and River City Ransom (school rival)

**Comment by n3tn0de** [comment]
I think we should put Bo as Act 2 boss, or in the end of first, and put Local Drunks from Act 2 in the beginning as tutorial punching bags. 
One enemy will not be enough to get the grip on controls and mechanics.

**Comment by n3tn0de** [comment]
We should add an elevator part before final boss

**Comment by petarov** [comment]
Made a few story adjustments and added opening scene script. What is left is to adjust the **attack waves**, which we can do while testing the levels and **dialogs**, which I will leave for the last week depending on how far we are at and if we can have time to include them!
